# Generated by Django 2.2.2 on 2019-06-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(verbose_name='date in invoice'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_creation',
            field=models.DateField(verbose_name='date creation in system'),
        ),
    ]
